name: unit tests

on:
  push:
    branches: 
      - 'trial/**'
      - master

env:
  MSSQL_SERVER: localhost,1433
  MSSQL_USER: sa
  MSSQL_PWD: Passw0rd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.100-rc.2.23502.2

      # Install SQL Server
      - name: Setup SQL Server
        run: docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$MSSQL_PWD" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2019-latest

      # Perform unit tests
      - name: Perform unit tests
        run: dotnet test EFCore.IndexAttribute.Test -l "console;verbosity=normal" -v:q --nologo
